import type { UpgradeEffect } from '@swarm-script/shared';

export const UPGRADES: UpgradeEffect[] = [
  {
    id: 'arc-relay',
    name: 'Arc relay',
    description: 'Squad projectiles chain once to a nearby hostile.',
    effect: 'chain',
    synergy: 'Pairs with rapid fire and marks.',
  },
  {
    id: 'volatile-overcharge',
    name: 'Volatile overcharge',
    description: 'Overcharge activation detonates a close-range pulse.',
    effect: 'overchargeBlast',
    role: 'striker',
    synergy: 'Rewards aggressive Striker positioning.',
  },
  {
    id: 'mirror-aegis',
    name: 'Mirror aegis',
    description: 'Shield reflects 35% of blocked projectile damage.',
    effect: 'shieldReflect',
    role: 'guardian',
    synergy: 'Punishes Snipers while protecting allies.',
  },
  {
    id: 'viral-designator',
    name: 'Viral designator',
    description: 'A defeated marked enemy passes Mark to a nearby target.',
    effect: 'markSpread',
    role: 'scout',
    synergy: 'Keeps focus damage moving through groups.',
  },
  {
    id: 'bounty-circuit',
    name: 'Bounty circuit',
    description: 'Defeating a marked enemy restores 14 squad energy.',
    effect: 'markedEnergy',
    role: 'scout',
    synergy: 'Feeds every robot ability.',
  },
  {
    id: 'cryo-criticals',
    name: 'Cryo criticals',
    description: 'Every fifth squad shot slows its target briefly.',
    effect: 'criticalSlow',
    synergy: 'Creates space against Swarmers.',
  },
  {
    id: 'trident-bore',
    name: 'Trident bore',
    description: 'Every third squad projectile pierces one target.',
    effect: 'pierce',
    synergy: 'Excels against aligned packs and Splitters.',
  },
  {
    id: 'proximity-charge',
    name: 'Proximity charge',
    description: 'Enemies defeated at close range burst into splash damage.',
    effect: 'closeExplosion',
    synergy: 'Combines with Overcharge dives and Shield.',
  },
  {
    id: 'survival-servos',
    name: 'Survival servos',
    description: 'Robots below 35% health gain 45% movement speed.',
    effect: 'lowHealthSpeed',
    synergy: 'Makes retreat rules dramatically stronger.',
  },
  {
    id: 'guardian-dynamo',
    name: 'Guardian dynamo',
    description: 'Guardian gains energy whenever Shield blocks damage.',
    effect: 'guardianBattery',
    role: 'guardian',
    synergy: 'Extends defensive ability chains.',
  },
  {
    id: 'evasive-clock',
    name: 'Evasive clock',
    description: 'Scout ability cooldown accelerates while avoiding damage.',
    effect: 'scoutEvasion',
    role: 'scout',
    synergy: 'Rewards mobile scripts and careful spacing.',
  },
  {
    id: 'lone-target-protocol',
    name: 'Lone target protocol',
    description: 'Striker deals 35% bonus damage to isolated enemies.',
    effect: 'isolatedDamage',
    role: 'striker',
    synergy: 'Finishes Snipers and the Commander.',
  },
  {
    id: 'overclocked-rounds',
    name: 'Overclocked rounds',
    description: 'Squad weapon damage increases by 18%.',
    effect: 'damage',
    multiplier: 1.18,
    synergy: 'A reliable foundation for every build.',
  },
  {
    id: 'targeting-lattice',
    name: 'Targeting lattice',
    description: 'Squad attack range increases by 16%.',
    effect: 'range',
    multiplier: 1.16,
    synergy: 'Helps contest Snipers and avoid Bulwark fronts.',
  },
  {
    id: 'ceramic-shells',
    name: 'Ceramic shells',
    description: 'Restore the squad and increase maximum health by 18%.',
    effect: 'health',
    multiplier: 1.18,
    synergy: 'Stabilizes risky offensive builds.',
  },
];
